ERROR - 2022-11-11 03:46:11 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-11-11 03:46:11 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `auth_tokens`
WHERE `selector` = :selector:', [...], false)
 3 VENDORPATH\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
 4 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a196be537dd')
 5 VENDORPATH\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
 6 SYSTEMPATH\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 7 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-11-11 03:46:15 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-11-11 03:46:15 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `auth_tokens`
WHERE `selector` = :selector:', [...], false)
 3 VENDORPATH\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
 4 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a196be537dd')
 5 VENDORPATH\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
 6 SYSTEMPATH\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 7 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-11-11 03:46:20 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-11-11 03:46:20 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `auth_tokens`
WHERE `selector` = :selector:', [...], false)
 3 VENDORPATH\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
 4 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a196be537dd')
 5 VENDORPATH\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
 6 SYSTEMPATH\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 7 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-11-11 03:46:24 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-11-11 03:46:24 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `auth_tokens`
WHERE `selector` = :selector:', [...], false)
 3 VENDORPATH\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
 4 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a196be537dd')
 5 VENDORPATH\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
 6 SYSTEMPATH\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 7 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-11-11 03:46:29 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-11-11 03:46:29 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `auth_tokens`
WHERE `selector` = :selector:', [...], false)
 3 VENDORPATH\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
 4 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a196be537dd')
 5 VENDORPATH\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
 6 SYSTEMPATH\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 7 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-11-11 03:46:33 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a1...')
#5 C:\xampp\htdocs\codeigniter4-framework-872c8fb\vendor\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
#6 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#7 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('/', 'before')
#8 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\codeigniter4-framework-872c8fb\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\codeigniter4-framework-872c8fb\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-11-11 03:46:33 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `auth_tokens`
WHERE `selector` = :selector:', [...], false)
 3 VENDORPATH\myth\auth\src\Models\LoginModel.php(53): CodeIgniter\Database\BaseBuilder->get()
 4 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(87): Myth\Auth\Models\LoginModel->getRememberToken('93c72619f9196a196be537dd')
 5 VENDORPATH\myth\auth\src\Filters\LoginFilter.php(29): Myth\Auth\Authentication\LocalAuthenticator->check()
 6 SYSTEMPATH\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 7 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
